name: "자유 대화"
description: "자유롭게 AI 및 기타 주제에 대해 이야기하세요."
title: "[자유 대화] 제목을 입력하세요"
labels: []
body:
  - type: textarea
    id: topic
    attributes:
      label: "💬 대화 주제"
      description: "이야기하고 싶은 주제를 자유롭게 적어주세요."
    validations:
      required: true
